# Generated by Django 5.2.17 on 2026-08-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('tool', 'Tool')], max_length=20)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
